services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '50051:50051'
      - '5678:5678'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boilerplate_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:7.0'
    container_name: 'my-redis'
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
